# Currently doesn't actually do anything.
allow-wars: true

# Set this to false to disable the faction map. It shouldn't cause lag, but just in case.
allow-faction-map: true

chat-include-group: true

# The discord token, or "null" if no discord server should be used.
discord-token: "null"